#!/usr/bin/env node
/**
 * v2.0.B.216 — Content database extractor.
 *
 * Reads public/lessons-ch{0..7}.json, outputs:
 *   - docs/content-db.md          full table per Q (chapter / lesson / id /
 *                                 type / question / answer / est_time_s)
 *   - docs/content-db-summary.md  per-chapter aggregates + 25% variance check
 *
 * Per-type estimated time (seconds):
 *   - tap-pairs (vocab intro): 45
 *   - tap-pairs (review):      40
 *   - narration:               30  (auto-advance after TTS)
 *   - listen-tf:               25  (Y/N quick decision)
 *   - listen-mc:               45  (4-option think)
 *   - listen-comprehension:    60  (deeper inference)
 *   - emoji-pick:              30  (visual)
 *   - tap-tiles:               50  (sentence ordering)
 *   - read-mc-with-audio:      45
 *   - listen-emoji:            30
 *   - type-what-you-hear:      75  (typing)
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

const TIME_S = {
  'tap-pairs': 42,            // avg vocab + review
  'narration': 30,
  'listen-tf': 25,
  'listen-tf-zh': 25,
  'listen-mc': 45,
  'listen-comprehension': 60,
  'emoji-pick': 30,
  'tap-tiles': 50,
  'read-mc-with-audio': 45,
  'listen-emoji': 30,
  'type-what-you-hear': 75,
};

const CHAPTER_TITLES = {
  0: 'Intro · 認識 Mochi 與奶奶',
  1: '桃太郎',
  2: '醜小鴨',
  3: '龜兔賽跑',
  4: '駱駝為什麼有駝峰',
  5: 'Baba Yaga',
  6: '六隻天鵝',
  7: '葉限',
};

function shortText(s, max = 60) {
  if (!s) return '';
  s = s.toString().replace(/\n/g, ' ').trim();
  return s.length > max ? s.slice(0, max - 1) + '…' : s;
}

function getAnswer(q) {
  if (q.type === 'narration') return '(auto-advance)';
  if (q.type === 'tap-pairs') {
    if (q.pairs) return q.pairs.map(p => `${p.left}=${p.right}`).join(' / ');
    return '(pairs)';
  }
  if (q.type === 'tap-tiles') return q.sentence || '(tiles)';
  if (q.type === 'listen-tf' || q.type === 'listen-tf-zh') {
    const idx = q.correctIndex ?? 0;
    return (q.options || ['Yes','No'])[idx];
  }
  if (Array.isArray(q.options)) {
    const idx = q.correctIndex ?? 0;
    const en = q.options[idx];
    const zh = q.optionsZh?.[idx];
    return zh ? `${en} (${zh})` : en;
  }
  return '(?)';
}

const rows = [];
const perChapter = {};

for (let ch = 0; ch <= 7; ch++) {
  const fp = path.join(ROOT, 'public', `lessons-ch${ch}.json`);
  if (!fs.existsSync(fp)) continue;
  const data = JSON.parse(fs.readFileSync(fp, 'utf-8'));
  const chStats = { lessons: data.length, qCount: 0, timeS: 0, typeCounts: {} };
  for (const lesson of data) {
    for (const q of lesson.questions || []) {
      const t = q.type;
      const time = TIME_S[t] || 40;
      const stem = q.question || q.questionEn || q.sentence || '';
      const answer = getAnswer(q);
      rows.push({
        ch,
        lesson: `Ch${ch}-${lesson.lessonInChapter}`,
        qId: q.id,
        type: t,
        speaker: q.speaker || '-',
        stem: shortText(stem, 60),
        answer: shortText(answer, 50),
        timeS: time,
      });
      chStats.qCount++;
      chStats.timeS += time;
      chStats.typeCounts[t] = (chStats.typeCounts[t] || 0) + 1;
    }
  }
  perChapter[ch] = chStats;
}

// ─── Write full DB ────────────────────────────────────────────────────
const dbLines = [
  `# Pickup Content DB — full Q table`,
  '',
  `Auto-generated by \`tools/_content-db.cjs\` from \`public/lessons-ch{0..7}.json\`.`,
  '',
  `**Total**: ${rows.length} Q across ${Object.keys(perChapter).length} chapters.`,
  '',
  `| Ch | Lesson | Q ID | Type | Speaker | Stem / Sentence | Answer | Time (s) |`,
  `|----|--------|------|------|---------|-----------------|--------|----------|`,
];
for (const r of rows) {
  const esc = s => String(s).replace(/\|/g, '\\|');
  dbLines.push(`| ${r.ch} | ${r.lesson} | \`${r.qId}\` | ${r.type} | ${r.speaker} | ${esc(r.stem)} | ${esc(r.answer)} | ${r.timeS} |`);
}
fs.writeFileSync(path.join(ROOT, 'docs', 'content-db.md'), dbLines.join('\n') + '\n', 'utf-8');

// ─── Write summary ────────────────────────────────────────────────────
const totalQ = rows.length;
const totalTime = rows.reduce((s, r) => s + r.timeS, 0);
const avgPerCh = Math.round(totalQ / Object.keys(perChapter).length);
const tolerance = 0.25;
const lowBand = Math.round(avgPerCh * (1 - tolerance));
const highBand = Math.round(avgPerCh * (1 + tolerance));

const sumLines = [
  `# Pickup Content DB — per-chapter summary`,
  '',
  `**Generated**: ${new Date().toISOString()}`,
  '',
  `## Aggregate`,
  '',
  `- **Total Q**: ${totalQ}`,
  `- **Total play time est**: ${Math.round(totalTime / 60)} min`,
  `- **Avg Q per chapter**: ${avgPerCh}`,
  `- **25% tolerance band**: ${lowBand} ≤ Q ≤ ${highBand}`,
  '',
  `## Per chapter (with 25% tolerance check)`,
  '',
  `| Ch | Title | Lessons | Q count | Avg Q/lesson | Total time (min) | Variance from avg | Tolerance |`,
  `|----|-------|---------|---------|--------------|------------------|-------------------|-----------|`,
];
for (let ch = 0; ch <= 7; ch++) {
  const s = perChapter[ch];
  if (!s) continue;
  const variance = Math.round((s.qCount - avgPerCh) / avgPerCh * 100);
  const inBand = s.qCount >= lowBand && s.qCount <= highBand;
  const sign = variance > 0 ? '+' : '';
  sumLines.push(`| ${ch} | ${CHAPTER_TITLES[ch] || ''} | ${s.lessons} | ${s.qCount} | ${(s.qCount / s.lessons).toFixed(1)} | ${Math.round(s.timeS / 60)} | ${sign}${variance}% | ${inBand ? '✓' : '⚠️ OUT'} |`);
}

sumLines.push('');
sumLines.push(`## Q type distribution per chapter`);
sumLines.push('');
const allTypes = new Set();
for (const s of Object.values(perChapter)) for (const t of Object.keys(s.typeCounts)) allTypes.add(t);
const typesArr = [...allTypes].sort();
sumLines.push(`| Ch | ${typesArr.join(' | ')} |`);
sumLines.push(`|----|${typesArr.map(()=>'---').join('|')}|`);
for (let ch = 0; ch <= 7; ch++) {
  const s = perChapter[ch];
  if (!s) continue;
  const cells = typesArr.map(t => s.typeCounts[t] || 0);
  sumLines.push(`| ${ch} | ${cells.join(' | ')} |`);
}

fs.writeFileSync(path.join(ROOT, 'docs', 'content-db-summary.md'), sumLines.join('\n') + '\n', 'utf-8');

console.log(`OK   docs/content-db.md (${rows.length} rows)`);
console.log(`OK   docs/content-db-summary.md`);
console.log(`\n[CURRENT STATE]`);
console.log(`Total Q: ${totalQ}, total time: ${Math.round(totalTime/60)} min`);
console.log(`Avg per chapter: ${avgPerCh}, 25% tolerance band: ${lowBand}-${highBand}`);
console.log(`\nPer chapter:`);
for (let ch = 0; ch <= 7; ch++) {
  const s = perChapter[ch];
  if (!s) continue;
  const variance = Math.round((s.qCount - avgPerCh) / avgPerCh * 100);
  const inBand = s.qCount >= lowBand && s.qCount <= highBand;
  console.log(`  Ch${ch} ${CHAPTER_TITLES[ch] || ''}: ${s.qCount} Q (${(s.qCount/s.lessons).toFixed(1)}/lesson), variance ${variance > 0 ? '+' : ''}${variance}% ${inBand ? '✓' : '⚠️ OUT'}`);
}
