#!/usr/bin/env node
/**
 * v2.0.B.216 — Content database extractor.
 *
 * Reads public/lessons-ch{0..7}.json, outputs:
 *   - docs/content-db.md          full table per Q (chapter / lesson / id /
 *                                 type / question / answer / est_time_s)
 *   - docs/content-db-summary.md  per-chapter aggregates + 25% variance check
 *
 * Per-type estimated time (seconds):
 *   - tap-pairs (vocab intro): 45
 *   - tap-pairs (review):      40
 *   - narration:               30  (auto-advance after TTS)
 *   - listen-tf:               25  (Y/N quick decision)
 *   - listen-mc:               45  (4-option think)
 *   - listen-comprehension:    60  (deeper inference)
 *   - emoji-pick:              30  (visual)
 *   - tap-tiles:               50  (sentence ordering)
 *   - read-mc-with-audio:      45
 *   - listen-emoji:            30
 *   - type-what-you-hear:      75  (typing)
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// v2.0.B.217: revised time estimates for 5 min/lesson budget
// Per user '數量要照每個小節只能花五分鐘'
const TIME_S = {
  'tap-pairs': 30,            // 4 pairs × 7s — vocab intro
  'narration': 15,            // ~10s TTS + 2s dwell + advance
  'listen-tf': 20,            // listen + Y/N tap
  'listen-tf-zh': 20,
  'listen-mc': 35,            // listen + read 4 options + tap
  'listen-comprehension': 45, // listen + inference + tap
  'emoji-pick': 25,           // visual quick
  'tap-tiles': 35,            // sentence ordering
  'read-mc-with-audio': 35,
  'listen-emoji': 25,
  'type-what-you-hear': 60,   // typing slowest
};
const LESSON_BUDGET_S = 300;  // 5 min

const CHAPTER_TITLES = {
  0: 'Intro · 認識 Mochi 與奶奶',
  1: '桃太郎',
  2: '醜小鴨',
  3: '龜兔賽跑',
  4: '駱駝為什麼有駝峰',
  5: 'Baba Yaga',
  6: '六隻天鵝',
  7: '葉限',
};

// v2.0.B.220: hook type per lesson (per docs/research/chapter-ending-hook-design.md)
// B1 物理懸念 / B2 情緒翻轉 / B3 資訊缺口 / B4 期待加速 / B5 道德兩難 / B6 預言種子
const HOOK_MAP = {
  // Ch1 桃太郎 (v6 emotional peak cut applied)
  'kt-ch1-l1': { type: 'B3',     inquiry: '那大紅色的是什麼?',         canon: 'momotaro.md#beat-1-setup' },
  'kt-ch1-l2': { type: 'B4+B3',  inquiry: '桃子裡是什麼?是嬰兒?活的?', canon: 'momotaro.md#beat-2-discovery' },
  'kt-ch1-l3': { type: 'B5+B2',  inquiry: '父母會讓他走嗎?',           canon: 'momotaro.md#beat-3-birth' },
  'kt-ch1-l4': { type: 'B4',     inquiry: '狗會跟?還會遇誰?',          canon: 'momotaro.md#beat-4-mission' },
  'kt-ch1-l5': { type: 'B6+B1',  inquiry: '島上為何安靜?是埋伏?',       canon: 'momotaro.md#beat-5-departure' },
  'kt-ch1-l6': { type: 'B2',     inquiry: '鬼王怎知他名字?陷阱?',       canon: 'momotaro.md#beat-6-battle' },
  'kt-ch1-l7': { type: 'B6 (open)', inquiry: '(開放結局, 留後鉤)',     canon: 'momotaro.md#beat-7-victory' },
  // Ch2-7 待 narrative-cut-analyst skill 重切
};

function shortText(s, max = 60) {
  if (!s) return '';
  s = s.toString().replace(/\n/g, ' ').trim();
  return s.length > max ? s.slice(0, max - 1) + '…' : s;
}

function getAnswer(q) {
  if (q.type === 'narration') return '(auto-advance)';
  if (q.type === 'tap-pairs') {
    if (q.pairs) return q.pairs.map(p => `${p.left}=${p.right}`).join(' / ');
    return '(pairs)';
  }
  if (q.type === 'tap-tiles') return q.sentence || '(tiles)';
  if (q.type === 'listen-tf' || q.type === 'listen-tf-zh') {
    const idx = q.correctIndex ?? 0;
    return (q.options || ['Yes','No'])[idx];
  }
  if (Array.isArray(q.options)) {
    const idx = q.correctIndex ?? 0;
    const en = q.options[idx];
    const zh = q.optionsZh?.[idx];
    return zh ? `${en} (${zh})` : en;
  }
  return '(?)';
}

const rows = [];
const perChapter = {};

// v2.0.B.217: skip Ch0 per user '不用放到數據庫裡面'
for (let ch = 1; ch <= 7; ch++) {
  const fp = path.join(ROOT, 'public', `lessons-ch${ch}.json`);
  if (!fs.existsSync(fp)) continue;
  const data = JSON.parse(fs.readFileSync(fp, 'utf-8'));
  const chStats = { lessons: data.length, qCount: 0, timeS: 0, typeCounts: {}, lessonsOverBudget: 0 };
  for (const lesson of data) {
    let lessonTime = 0;
    for (const q of lesson.questions || []) {
      const t = q.type;
      const time = TIME_S[t] || 40;
      const stem = q.question || q.questionEn || q.sentence || '';
      const answer = getAnswer(q);
      rows.push({
        ch,
        lesson: `Ch${ch}-${lesson.lessonInChapter}`,
        qId: q.id,
        type: t,
        speaker: q.speaker || '-',
        stem: shortText(stem, 60),
        answer: shortText(answer, 50),
        timeS: time,
      });
      chStats.qCount++;
      chStats.timeS += time;
      lessonTime += time;
      chStats.typeCounts[t] = (chStats.typeCounts[t] || 0) + 1;
    }
    if (lessonTime > LESSON_BUDGET_S) chStats.lessonsOverBudget++;
  }
  perChapter[ch] = chStats;
}

// ─── Write full DB ────────────────────────────────────────────────────
const dbLines = [
  `# Pickup Content DB — full Q table`,
  '',
  `Auto-generated by \`tools/_content-db.cjs\` from \`public/lessons-ch{0..7}.json\`.`,
  '',
  `**Total**: ${rows.length} Q across ${Object.keys(perChapter).length} chapters.`,
  '',
  `| Ch | Lesson | Q ID | Type | Speaker | Stem / Sentence | Answer | Time (s) |`,
  `|----|--------|------|------|---------|-----------------|--------|----------|`,
];
for (const r of rows) {
  const esc = s => String(s).replace(/\|/g, '\\|');
  dbLines.push(`| ${r.ch} | ${r.lesson} | \`${r.qId}\` | ${r.type} | ${r.speaker} | ${esc(r.stem)} | ${esc(r.answer)} | ${r.timeS} |`);
}
fs.writeFileSync(path.join(ROOT, 'docs', 'content-db.md'), dbLines.join('\n') + '\n', 'utf-8');

// ─── Write summary ────────────────────────────────────────────────────
const totalQ = rows.length;
const totalTime = rows.reduce((s, r) => s + r.timeS, 0);
const avgPerCh = Math.round(totalQ / Object.keys(perChapter).length);
const tolerance = 0.25;
const lowBand = Math.round(avgPerCh * (1 - tolerance));
const highBand = Math.round(avgPerCh * (1 + tolerance));

const sumLines = [
  `# Pickup Content DB — per-chapter summary`,
  '',
  `**Generated**: ${new Date().toISOString()}`,
  '',
  `## Aggregate`,
  '',
  `- **Total Q**: ${totalQ}`,
  `- **Total play time est**: ${Math.round(totalTime / 60)} min`,
  `- **Avg Q per chapter**: ${avgPerCh}`,
  `- **25% tolerance band**: ${lowBand} ≤ Q ≤ ${highBand}`,
  '',
  `## Per chapter (with 25% tolerance check)`,
  '',
  `| Ch | Title | Lessons | Q count | Avg Q/lesson | Avg lesson time (5 min budget) | Variance from avg | Tolerance |`,
  `|----|-------|---------|---------|--------------|--------------------------------|-------------------|-----------|`,
];
for (let ch = 1; ch <= 7; ch++) {
  const s = perChapter[ch];
  if (!s) continue;
  const variance = Math.round((s.qCount - avgPerCh) / avgPerCh * 100);
  const inBand = s.qCount >= lowBand && s.qCount <= highBand;
  const avgLessonTime = Math.round(s.timeS / s.lessons);
  const sign = variance > 0 ? '+' : '';
  const budgetMark = avgLessonTime <= LESSON_BUDGET_S ? '✓' : `⚠️ ${avgLessonTime}s>${LESSON_BUDGET_S}s`;
  sumLines.push(`| ${ch} | ${CHAPTER_TITLES[ch] || ''} | ${s.lessons} | ${s.qCount} | ${(s.qCount / s.lessons).toFixed(1)} | ${avgLessonTime}s/lesson ${budgetMark} | ${sign}${variance}% | ${inBand ? '✓' : '⚠️ OUT'} |`);
}

sumLines.push('');
sumLines.push(`## Per-lesson hook ending (v6, emotional peak cut)`);
sumLines.push('');
sumLines.push(`Per docs/research/chapter-ending-hook-design.md framework B1-B6.`);
sumLines.push(`Hook coverage: Ch1 ✓ applied. Ch2-7 待 narrative-cut-analyst skill 重切.`);
sumLines.push('');
sumLines.push(`| Lesson ID | Story Beat | Hook Type | Inquiry Question | Canon Ref |`);
sumLines.push(`|-----------|------------|-----------|------------------|-----------|`);
for (let ch = 1; ch <= 7; ch++) {
  const fp = path.join(ROOT, 'public', `lessons-ch${ch}.json`);
  if (!fs.existsSync(fp)) continue;
  const data = JSON.parse(fs.readFileSync(fp, 'utf-8'));
  for (const lesson of data) {
    const hook = HOOK_MAP[lesson.id];
    const hookType = hook?.type || '_(no hook yet)_';
    const inquiry = hook?.inquiry || '_-_';
    const canon = hook?.canon ? `[${hook.canon}](../docs/canon/${hook.canon})` : '_-_';
    sumLines.push(`| \`${lesson.id}\` | ${lesson.storyBeat || ''} | ${hookType} | ${inquiry} | ${canon} |`);
  }
}

sumLines.push('');
sumLines.push(`## Q type distribution per chapter`);
sumLines.push('');
const allTypes = new Set();
for (const s of Object.values(perChapter)) for (const t of Object.keys(s.typeCounts)) allTypes.add(t);
const typesArr = [...allTypes].sort();
sumLines.push(`| Ch | ${typesArr.join(' | ')} |`);
sumLines.push(`|----|${typesArr.map(()=>'---').join('|')}|`);
for (let ch = 1; ch <= 7; ch++) {
  const s = perChapter[ch];
  if (!s) continue;
  const cells = typesArr.map(t => s.typeCounts[t] || 0);
  sumLines.push(`| ${ch} | ${cells.join(' | ')} |`);
}

fs.writeFileSync(path.join(ROOT, 'docs', 'content-db-summary.md'), sumLines.join('\n') + '\n', 'utf-8');

console.log(`OK   docs/content-db.md (${rows.length} rows)`);
console.log(`OK   docs/content-db-summary.md`);
console.log(`\n[CURRENT STATE]`);
console.log(`Total Q: ${totalQ}, total time: ${Math.round(totalTime/60)} min`);
console.log(`Avg per chapter: ${avgPerCh}, 25% tolerance band: ${lowBand}-${highBand}`);
console.log(`\nPer chapter (Ch0 excluded, 5 min/lesson budget):`);
for (let ch = 1; ch <= 7; ch++) {
  const s = perChapter[ch];
  if (!s) continue;
  const variance = Math.round((s.qCount - avgPerCh) / avgPerCh * 100);
  const inBand = s.qCount >= lowBand && s.qCount <= highBand;
  const avgT = Math.round(s.timeS / s.lessons);
  const budgetMark = avgT <= LESSON_BUDGET_S ? '✓' : `⚠️ ${avgT}s>300s`;
  console.log(`  Ch${ch} ${CHAPTER_TITLES[ch] || ''}: ${s.qCount} Q (${(s.qCount/s.lessons).toFixed(1)}/lesson, ${avgT}s avg ${budgetMark}), variance ${variance > 0 ? '+' : ''}${variance}% ${inBand ? '✓' : '⚠️ OUT'}`);
}
