#!/usr/bin/env node
/**
 * Translate every unique English option string from lessons-ch*.json
 * into A2-level Chinese, then write optionsZh[] back into the JSON files
 * preserving option order.
 *
 * Strategy:
 *   1. Build comprehensive English->Chinese dictionary (DICT) covering
 *      words + 2-6-word phrases found in lessons-ch*.json options.
 *   2. translate(en) tries:
 *        a) DICT[exact lowercase]
 *        b) Special placeholder/name handling
 *        c) Compositional fallback: split on prepositions/copulas, lookup each.
 *   3. Write optionsZh as a NEW field, never mutate options/correctIndex/etc.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { OVERRIDES } from './translate-overrides.js';

const repoRoot = 'C:/Users/acer/Desktop/wordwar';
const wordHints = JSON.parse(readFileSync(resolve(repoRoot, 'public/word-hints.json'), 'utf8'));

// Normalize word-hints to lowercase keys, simple gloss (strip "/ second sense")
const HINTS = {};
for (const [k, v] of Object.entries(wordHints)) {
  HINTS[k.toLowerCase()] = String(v).split('/')[0].split('（')[0].trim();
}

// ============================================================
// Custom A2 dictionary — single words + common phrases
// covers all option strings in lessons-ch1..8.json
// ============================================================
const DICT = {
  // pronouns / determiners / connectives
  "a": "一個", "an": "一個", "the": "那個", "and": "和", "or": "或",
  "i": "我", "me": "我", "my": "我的", "mine": "我的",
  "you": "你", "your": "你的", "yours": "你的",
  "he": "他", "him": "他", "his": "他的",
  "she": "她", "her": "她的", "hers": "她的",
  "it": "它", "its": "它的", "they": "他們", "them": "他們", "their": "他們的",
  "we": "我們", "us": "我們", "our": "我們的",
  "this": "這個", "that": "那個", "these": "這些", "those": "那些",
  "some": "一些", "any": "任何", "other": "其他的", "another": "另一個",
  "all": "全部", "none": "沒有", "nothing": "沒事", "something": "某事", "anything": "任何事",
  "no": "不", "yes": "是", "maybe": "也許", "sure": "當然", "never": "從不",
  "always": "總是", "sometimes": "有時", "often": "經常", "rarely": "很少",
  "now": "現在", "then": "然後", "later": "稍後", "soon": "很快",
  "today": "今天", "tomorrow": "明天", "yesterday": "昨天", "tonight": "今晚",
  "early": "早", "late": "晚", "first": "第一", "last": "最後",
  "here": "這裡", "there": "那裡", "where": "哪裡", "when": "什麼時候",
  "why": "為什麼", "how": "怎麼", "who": "誰", "what": "什麼",
  "very": "非常", "too": "太", "so": "如此", "much": "很多", "many": "許多",
  "more": "更多", "less": "更少", "most": "最多", "least": "最少", "again": "再次",
  "still": "仍然", "yet": "還", "already": "已經", "ever": "曾經",
  "for": "為了", "with": "和", "without": "沒有", "to": "到", "from": "從",
  "in": "在裡面", "on": "在上面", "at": "在", "by": "靠近", "of": "的",
  "up": "向上", "down": "向下", "out": "外面", "outside": "外面",
  "inside": "裡面", "above": "上方", "below": "下方", "under": "下面", "over": "上面",
  "into": "進入", "across": "跨越", "along": "沿著", "around": "周圍",
  "near": "附近", "far": "遠", "behind": "後面", "front": "前面",
  "back": "後面", "side": "旁邊", "between": "之間", "next": "下一個",

  // numbers
  "one": "一", "two": "二", "three": "三", "four": "四", "five": "五",
  "six": "六", "seven": "七", "eight": "八", "nine": "九", "ten": "十",
  "eleven": "十一", "twelve": "十二", "fifteen": "十五", "sixteen": "十六",
  "twenty": "二十", "fifty": "五十", "once": "一次", "twice": "兩次",
  "third": "第三", "single": "單一", "double": "雙", "half": "一半",

  // days / months / time
  "monday": "星期一", "tuesday": "星期二", "wednesday": "星期三",
  "thursday": "星期四", "friday": "星期五", "saturday": "星期六", "sunday": "星期日",
  "morning": "早上", "afternoon": "下午", "evening": "傍晚", "night": "夜晚",
  "midnight": "午夜", "noon": "中午", "dawn": "黎明",
  "sundown": "日落", "sunrise": "日出", "sunset": "日落",
  "spring": "春天", "summer": "夏天", "autumn": "秋天", "winter": "冬天", "fall": "秋天",
  "weather": "天氣", "season": "季節", "year": "年", "month": "月",
  "week": "週", "weekly": "每週", "day": "天", "hour": "小時", "hours": "小時",
  "minute": "分鐘", "minutes": "分鐘", "time": "時間", "times": "次",
  "august": "八月", "ago": "以前", "forever": "永遠",

  // family / people
  "mom": "媽媽", "mother": "媽媽", "dad": "爸爸", "father": "爸爸",
  "grandma": "奶奶", "grandpa": "爺爺", "child": "孩子", "children": "孩子們",
  "baby": "寶寶", "boy": "男孩", "girl": "女孩", "man": "男人", "woman": "女人",
  "men": "男人們", "women": "女人們", "kid": "小孩", "kids": "小孩",
  "son": "兒子", "daughter": "女兒", "brother": "哥哥", "sister": "姊姊",
  "siblings": "兄弟姊妹", "family": "家人", "friend": "朋友", "friends": "朋友",
  "friendly": "友善的", "neighbor": "鄰居", "neighbors": "鄰居",
  "stranger": "陌生人", "guest": "客人", "leader": "領袖",
  "wife": "妻子", "husband": "丈夫", "queen": "王后", "king": "國王",
  "prince": "王子", "princess": "公主", "doctor": "醫生", "nurse": "護士",
  "teacher": "老師", "farmer": "農夫", "farmers": "農夫們",
  "fisher": "漁夫", "fishers": "漁夫們", "fisherman": "漁夫",
  "hunter": "獵人", "hunters": "獵人們", "baker": "麵包師", "bakers": "麵包師",
  "cook": "廚師", "guard": "守衛", "messenger": "信使", "soldier": "士兵",
  "soldiers": "士兵", "witch": "巫婆", "general": "將軍",
  "stepmother": "繼母", "stepmothers": "繼母", "stepsister": "繼姊",
  "villager": "村民", "villagers": "村民", "rider": "騎士",
  "groom": "新郎", "owner": "主人", "owners": "主人",
  "listener": "聽眾", "searcher": "尋找者", "solver": "解決者",
  "traveler": "旅人", "forester": "森林人", "caller": "呼叫者",
  "ally": "盟友", "foe": "敵人", "enemy": "敵人",
  "nephew": "侄兒", "uncle": "叔叔", "aunt": "阿姨",

  // animals
  "cat": "貓", "cats": "貓", "kitten": "小貓", "dog": "狗", "dogs": "狗",
  "puppy": "小狗", "bird": "鳥", "birds": "鳥", "fish": "魚",
  "horse": "馬", "horses": "馬", "cow": "牛", "cows": "牛",
  "sheep": "羊", "lamb": "小羊", "pig": "豬", "rabbit": "兔子", "rabbits": "兔子",
  "mouse": "老鼠", "mice": "老鼠", "snake": "蛇", "snakes": "蛇",
  "frog": "青蛙", "fox": "狐狸", "wolf": "狼", "wolves": "狼",
  "bear": "熊", "lion": "獅子", "tiger": "老虎", "monkey": "猴子",
  "deer": "鹿", "duck": "鴨子", "duckling": "小鴨", "ducks": "鴨子",
  "swan": "天鵝", "swans": "天鵝", "hen": "母雞", "chicken": "雞",
  "crow": "烏鴉", "owl": "貓頭鷹", "sparrow": "麻雀", "pheasant": "雉雞",
  "dove": "鴿子", "pigeons": "鴿子", "eagle": "老鷹", "hare": "兔子",
  "tortoise": "烏龜", "turtle": "烏龜", "camel": "駱駝", "leopard": "豹",
  "llama": "羊駝", "snail": "蝸牛", "moth": "蛾", "worm": "蟲",
  "bees": "蜜蜂", "fly": "蒼蠅", "bugs": "蟲子", "jade": "玉",
  "shiba": "柴犬", "demon": "妖怪", "demons": "妖怪",
  "ghost": "鬼", "djinn": "精靈", "god": "神", "gods": "眾神",

  // body parts
  "head": "頭", "hair": "頭髮", "face": "臉", "eye": "眼睛", "eyes": "眼睛",
  "nose": "鼻子", "mouth": "嘴巴", "lip": "嘴唇", "lips": "嘴唇",
  "ear": "耳朵", "ears": "耳朵", "tooth": "牙齒", "teeth": "牙齒",
  "tongue": "舌頭", "throat": "喉嚨", "neck": "脖子", "chest": "胸部",
  "back": "背", "arm": "手臂", "arms": "手臂", "hand": "手", "hands": "手",
  "finger": "手指", "fingers": "手指", "fist": "拳頭", "leg": "腿", "legs": "腿",
  "foot": "腳", "feet": "腳", "toe": "腳趾", "knee": "膝蓋", "skin": "皮膚",
  "tail": "尾巴", "wing": "翅膀", "wings": "翅膀", "paw": "爪子", "paws": "爪子",
  "beak": "鳥嘴", "shell": "殼", "fur": "毛", "feathers": "羽毛",
  "collar": "項圈", "hump": "駝峰", "humph": "哼", "horn": "角", "horns": "角",
  "claw": "爪", "claws": "爪", "shadow": "影子", "reflection": "倒影",

  // nature / places
  "tree": "樹", "trees": "樹", "branch": "樹枝", "leaf": "葉子", "leaves": "葉子",
  "flower": "花", "flowers": "花", "grass": "草", "bush": "灌木", "bushes": "灌木",
  "reed": "蘆葦", "pine": "松樹", "oak": "橡樹", "rose": "玫瑰",
  "thorns": "荊棘", "wood": "木頭", "woods": "森林", "forest": "森林",
  "garden": "花園", "yard": "院子", "park": "公園", "field": "田地",
  "farm": "農場", "barn": "穀倉", "hill": "山丘", "hills": "山丘",
  "mountain": "山", "valley": "山谷", "cave": "洞穴", "hole": "洞",
  "river": "河", "lake": "湖", "lakes": "湖", "pond": "池塘", "sea": "海",
  "ocean": "海洋", "shore": "岸邊", "bank": "岸", "swamp": "沼澤",
  "desert": "沙漠", "sand": "沙", "sky": "天空", "sun": "太陽", "moon": "月亮",
  "star": "星星", "stars": "星星", "cloud": "雲", "clouds": "雲",
  "rain": "雨", "snow": "雪", "wind": "風", "storm": "暴風雨", "fog": "霧",
  "ice": "冰", "fire": "火", "smoke": "煙", "water": "水",
  "earth": "大地", "ground": "地面", "rock": "石頭", "stone": "石頭", "stones": "石頭",
  "dust": "灰塵", "mud": "泥巴", "road": "路", "path": "小路", "street": "街道",
  "alley": "巷子", "bridge": "橋", "gate": "門", "wall": "牆",
  "city": "城市", "town": "城鎮", "village": "村莊", "country": "鄉村",
  "house": "房子", "houses": "房子", "home": "家", "hut": "小屋",
  "barn": "穀倉", "tower": "塔", "porch": "門廊", "kitchen": "廚房",
  "room": "房間", "door": "門", "window": "窗", "chair": "椅子",
  "bed": "床", "table": "桌子", "shelf": "架子", "lamp": "燈",
  "candle": "蠟燭", "lantern": "燈籠", "stove": "爐子", "pot": "鍋",
  "bowl": "碗", "cup": "杯子", "plate": "盤子", "spoon": "湯匙",
  "knife": "刀", "jar": "罐子", "basket": "籃子", "box": "盒子",
  "bag": "袋子", "bags": "袋子", "envelope": "信封", "pocket": "口袋",
  "shop": "商店", "market": "市場", "port": "港口", "station": "車站",
  "festival": "節慶", "wedding": "婚禮", "school": "學校", "stage": "舞台",
  "island": "島嶼", "kingdom": "王國", "nest": "鳥巢", "den": "獸穴",

  // weather / sensations
  "hot": "熱", "cold": "冷", "warm": "溫暖", "cool": "涼", "cooler": "較涼",
  "colder": "更冷", "freezing": "冰凍", "frozen": "結凍", "icy": "冰冷",
  "wet": "濕", "dry": "乾", "soaking": "濕透", "sandy": "沙質",
  "thirsty": "口渴", "hungry": "餓", "sleepy": "想睡", "tired": "累",
  "rested": "休息好", "exhausted": "筋疲力盡", "weak": "虛弱", "strong": "強壯",
  "fresh": "新鮮", "stale": "不新鮮", "raw": "生的", "ripe": "熟的",
  "starry": "星光點點", "sunny": "晴朗", "shady": "陰涼", "stuffy": "悶",
  "fierce": "兇猛", "tame": "溫馴",

  // colors / qualities
  "red": "紅色", "orange": "橘色", "yellow": "黃色", "green": "綠色",
  "blue": "藍色", "purple": "紫色", "pink": "粉紅色", "brown": "棕色",
  "black": "黑色", "white": "白色", "grey": "灰色", "gray": "灰色",
  "gold": "金色", "golden": "金色", "silver": "銀色", "copper": "銅色",
  "color": "顏色", "shiny": "閃亮", "shine": "光輝", "bright": "明亮",
  "dark": "黑暗", "light": "光", "lit": "點亮", "dim": "昏暗",

  // size / shape
  "big": "大", "small": "小", "tiny": "微小", "huge": "巨大",
  "tall": "高", "short": "矮", "long": "長", "wide": "寬", "narrow": "窄",
  "thin": "瘦", "thick": "厚", "fat": "胖", "deep": "深", "shallow": "淺",
  "high": "高", "low": "低", "round": "圓", "flat": "平",
  "smaller": "更小", "bigger": "更大", "taller": "更高", "older": "更老",
  "younger": "更年輕", "stronger": "更強", "weaker": "更弱",
  "louder": "更大聲", "softer": "更輕", "smarter": "更聰明",

  // emotions
  "happy": "開心", "sad": "難過", "angry": "生氣", "mad": "氣憤",
  "scared": "害怕", "afraid": "害怕", "fearful": "害怕", "fear": "恐懼",
  "brave": "勇敢", "bold": "勇敢", "shy": "害羞", "calm": "冷靜",
  "kind": "善良", "mean": "壞心", "cruel": "殘忍", "rude": "粗魯",
  "gentle": "溫柔", "rough": "粗暴", "polite": "有禮貌",
  "proud": "驕傲", "humble": "謙虛", "smug": "得意", "overconfident": "過度自信",
  "confident": "有自信", "doubtful": "懷疑", "curious": "好奇",
  "amazed": "驚訝", "surprised": "驚訝", "shocked": "震驚",
  "confused": "困惑", "anxious": "焦慮", "nervous": "緊張",
  "stressed": "緊張", "frustrated": "沮喪", "regretful": "後悔",
  "ashamed": "羞愧", "heartbroken": "心碎", "lonely": "孤單", "lone": "孤單",
  "alone": "獨自", "uneasy": "不安", "sullen": "陰沉", "sober": "嚴肅",
  "joyful": "喜悅", "glad": "高興", "thrilled": "興奮", "excited": "興奮",
  "thankful": "感激", "grateful": "感激", "relieved": "鬆口氣",
  "comforted": "得到安慰", "comfortable": "舒適", "cozy": "舒適",
  "content": "滿足", "satisfied": "滿足", "peaceful": "平靜",
  "playful": "好玩", "silly": "傻氣", "funny": "有趣",
  "tempted": "受誘惑", "terrified": "嚇壞", "worried": "擔心",
  "sore": "酸痛", "hurt": "受傷", "ill": "生病", "sick": "生病",
  "smart": "聰明", "wise": "明智", "wiser": "更明智", "clever": "聰明",
  "fool": "傻瓜", "foolish": "愚笨", "fooled": "被騙",
  "lazy": "懶", "busy": "忙", "eager": "渴望", "patient": "有耐心",
  "patience": "耐心", "focused": "專注", "determined": "堅定",
  "serious": "嚴肅", "ready": "準備好", "hopeful": "充滿希望",
  "hopeless": "絕望", "thoughtful": "深思", "interested": "感興趣",
  "bored": "無聊", "boring": "無聊", "noisy": "吵", "quiet": "安靜",
  "silent": "沉默", "loud": "大聲", "wild": "狂野", "fierce": "兇猛",
  "graceful": "優雅", "ugly": "醜", "pretty": "漂亮", "beautiful": "美麗",
  "real": "真實", "fake": "假的", "magic": "魔法", "magical": "神奇",
  "lost": "迷路", "found": "找到", "free": "自由",
  "safe": "安全", "dangerous": "危險", "harm": "傷害",
  "right": "對的", "wrong": "錯的", "good": "好", "bad": "壞",
  "new": "新", "old": "舊", "ancient": "古老", "young": "年輕",
  "rich": "富有", "poor": "貧窮", "greedy": "貪心", "wealthy": "富有",
  "open": "打開", "closed": "關閉", "broken": "壞掉", "ruined": "毀壞",
  "empty": "空", "full": "滿", "alive": "活著", "dead": "死",
  "asleep": "睡著", "awake": "醒著", "ready": "準備好", "stiff": "僵硬",
  "tight": "緊", "loose": "鬆", "stuck": "卡住", "tidy": "整齊",
  "fancy": "華麗", "simple": "簡單", "plain": "樸素", "fast": "快",
  "slow": "慢", "quick": "快速", "slower": "更慢", "fancier": "更華麗",
  "swiftly": "迅速地", "quickly": "快速地", "slowly": "慢慢地",
  "softly": "輕輕地", "loudly": "大聲地", "gently": "溫柔地", "lightly": "輕輕地",
  "sweetly": "甜甜地", "kindly": "親切地", "angrily": "生氣地", "sadly": "悲傷地",
  "nervously": "緊張地", "wickedly": "邪惡地", "barely": "幾乎沒有",
  "hardly": "幾乎沒有", "shortly": "不久", "deeply": "深深地",
  "carefully": "小心地", "roughly": "粗魯地", "suddenly": "突然",
  "finally": "最後", "totally": "完全", "actually": "其實",

  // verbs (base + common inflections)
  "is": "是", "am": "是", "are": "是", "was": "是過去", "were": "是過去",
  "be": "成為", "been": "曾是", "being": "正在", "had": "有過",
  "has": "有", "have": "有", "having": "擁有",
  "do": "做", "does": "做", "did": "做過", "done": "做完", "doing": "在做",
  "go": "去", "goes": "去", "going": "去", "went": "去過", "gone": "去了",
  "come": "來", "comes": "來", "coming": "來", "came": "來過",
  "see": "看", "sees": "看", "seeing": "看", "saw": "看過", "seen": "看過",
  "look": "看", "looks": "看", "looking": "看著", "looked": "看過",
  "watch": "看", "watches": "看", "watching": "看著", "watched": "看過",
  "hear": "聽", "hears": "聽", "hearing": "聽", "heard": "聽過",
  "listen": "聽", "listens": "聽", "listening": "聽",
  "speak": "說", "speaks": "說", "spoke": "說過", "spoken": "說過",
  "say": "說", "says": "說", "said": "說過", "saying": "說",
  "tell": "告訴", "tells": "告訴", "told": "告訴", "telling": "告訴",
  "talk": "說話", "talks": "說話", "talking": "說話", "talked": "說過",
  "ask": "問", "asks": "問", "asking": "問", "asked": "問過",
  "answer": "回答", "answers": "回答", "answered": "回答過",
  "shout": "大叫", "shouts": "大叫", "shouting": "大叫", "shouted": "大叫過",
  "cry": "哭", "cries": "哭", "crying": "哭", "cried": "哭過",
  "laugh": "笑", "laughs": "笑", "laughing": "笑", "laughed": "笑過",
  "smile": "微笑", "smiles": "微笑", "smiled": "微笑過",
  "sing": "唱", "sings": "唱", "singing": "唱歌", "sang": "唱過", "sung": "唱過",
  "song": "歌", "songs": "歌",
  "dance": "跳舞", "dances": "跳舞", "dancing": "跳舞", "danced": "跳舞過",
  "play": "玩", "plays": "玩", "playing": "玩", "played": "玩過",
  "run": "跑", "runs": "跑", "running": "跑", "ran": "跑過",
  "walk": "走", "walks": "走", "walking": "走", "walked": "走過",
  "jump": "跳", "jumps": "跳", "jumping": "跳", "jumped": "跳過",
  "hop": "跳", "leap": "躍", "leaps": "躍", "leaped": "躍過",
  "climb": "爬", "climbs": "爬", "climbing": "爬",
  "crawl": "爬行", "crawls": "爬行",
  "swim": "游泳", "swims": "游泳", "swimming": "游泳", "swam": "游過",
  "fly": "飛", "flies": "飛", "flying": "飛", "flew": "飛過", "flown": "飛過",
  "sit": "坐", "sits": "坐", "sitting": "坐", "sat": "坐過",
  "stand": "站", "stands": "站", "standing": "站", "stood": "站過",
  "lie": "躺", "lies": "躺", "lay": "躺過", "laid": "放下",
  "sleep": "睡覺", "sleeps": "睡覺", "sleeping": "睡覺", "slept": "睡過",
  "wake": "醒", "wakes": "醒", "woke": "醒過", "waked": "醒過",
  "rest": "休息", "rests": "休息", "rested": "休息過",
  "eat": "吃", "eats": "吃", "ate": "吃過", "eaten": "吃過", "eating": "吃",
  "drink": "喝", "drinks": "喝", "drank": "喝過", "drinking": "喝",
  "cook": "煮", "cooks": "煮", "cooked": "煮過", "cooking": "煮",
  "bake": "烤", "bakes": "烤", "baked": "烤過",
  "feed": "餵", "feeds": "餵", "fed": "餵過",
  "make": "做", "makes": "做", "made": "做過", "making": "做",
  "take": "拿", "takes": "拿", "took": "拿過", "taken": "拿過",
  "bring": "帶來", "brings": "帶來", "brought": "帶來過", "bringing": "帶",
  "carry": "搬", "carries": "搬", "carried": "搬過",
  "give": "給", "gives": "給", "gave": "給過", "given": "給過",
  "get": "得到", "gets": "得到", "got": "得到過", "gotten": "得到",
  "put": "放", "puts": "放", "putting": "放",
  "set": "放", "sets": "放",
  "hold": "拿著", "holds": "拿著", "held": "拿著過", "holding": "拿著",
  "throw": "丟", "throws": "丟", "threw": "丟過", "thrown": "丟過",
  "drop": "掉", "drops": "掉", "dropped": "掉了", "dropping": "掉",
  "pull": "拉", "pulls": "拉", "pulled": "拉過",
  "push": "推", "pushes": "推", "pushed": "推過",
  "lift": "舉", "lifts": "舉", "lifted": "舉過",
  "lower": "放低", "lowers": "放低", "lowered": "放低",
  "open": "打開", "opens": "打開", "opened": "打開過", "opening": "打開",
  "close": "關上", "closes": "關上", "closed": "關上過",
  "turn": "轉", "turns": "轉", "turned": "轉過",
  "stop": "停", "stops": "停", "stopped": "停下", "stopping": "停下",
  "start": "開始", "starts": "開始", "started": "開始", "starting": "開始",
  "begin": "開始", "begins": "開始", "began": "開始", "beginning": "開始",
  "end": "結束", "ends": "結束", "ended": "結束過", "ending": "結束",
  "finish": "完成", "finishes": "完成", "finished": "完成", "finishing": "完成",
  "live": "住", "lives": "住", "lived": "住過", "living": "住",
  "die": "死", "dies": "死", "died": "死了", "dying": "快死",
  "love": "愛", "loves": "愛", "loved": "愛過", "loving": "愛",
  "like": "喜歡", "likes": "喜歡", "liked": "喜歡", "liking": "喜歡",
  "hate": "討厭", "hates": "討厭", "hated": "討厭",
  "want": "要", "wants": "要", "wanted": "要過", "wanting": "想要",
  "need": "需要", "needs": "需要", "needed": "需要", "needing": "需要",
  "wish": "希望", "wishes": "希望", "wished": "希望", "wishing": "希望",
  "hope": "希望", "hopes": "希望", "hoped": "希望", "hoping": "希望",
  "try": "試", "tries": "試", "tried": "試過", "trying": "試",
  "find": "找", "finds": "找", "found": "找到",
  "know": "知道", "knows": "知道", "knew": "知道過", "known": "知道",
  "think": "想", "thinks": "想", "thought": "想過", "thinking": "想",
  "feel": "感覺", "feels": "感覺", "felt": "感覺過", "feeling": "感覺",
  "learn": "學", "learns": "學", "learned": "學過", "learnt": "學過",
  "teach": "教", "teaches": "教", "taught": "教過",
  "read": "讀", "reads": "讀", "reading": "讀",
  "write": "寫", "writes": "寫", "wrote": "寫過", "writing": "寫",
  "buy": "買", "buys": "買", "bought": "買過", "buying": "買",
  "sell": "賣", "sells": "賣", "sold": "賣過", "selling": "賣",
  "pay": "付", "pays": "付", "paid": "付過",
  "win": "贏", "wins": "贏", "won": "贏過", "winning": "贏",
  "lose": "輸", "loses": "輸", "lost": "輸過",
  "help": "幫忙", "helps": "幫忙", "helped": "幫忙過", "helpful": "有用",
  "save": "救", "saves": "救", "saved": "救過",
  "wait": "等", "waits": "等", "waited": "等過", "waiting": "等",
  "stay": "留", "stays": "留", "stayed": "留下",
  "leave": "離開", "leaves": "離開", "left": "離開過", "leaving": "離開",
  "send": "送", "sends": "送", "sent": "送過",
  "follow": "跟隨", "follows": "跟隨", "followed": "跟過",
  "lead": "帶領", "leads": "帶領", "led": "帶過",
  "meet": "見面", "meets": "見面", "met": "見過",
  "join": "加入", "joins": "加入", "joined": "加入過",
  "share": "分享", "shares": "分享", "shared": "分享過",
  "fight": "打架", "fights": "打架", "fought": "打架過",
  "hide": "躲", "hides": "躲", "hid": "躲過", "hidden": "藏起",
  "show": "展示", "shows": "展示", "showed": "展示過", "shown": "展示",
  "use": "用", "uses": "用", "used": "用過",
  "break": "打破", "breaks": "打破", "broke": "打破", "broken": "壞掉",
  "bend": "彎", "bends": "彎", "bent": "彎",
  "warn": "警告", "warns": "警告",
  "scare": "嚇", "scares": "嚇", "scared": "嚇過",
  "chase": "追", "chases": "追",
  "bite": "咬", "bites": "咬", "bit": "咬過", "biting": "咬",
  "bark": "叫", "barks": "叫", "barked": "叫過", "barking": "叫",
  "purr": "呼嚕", "purrs": "呼嚕", "wag": "搖", "wags": "搖",
  "lick": "舔", "licks": "舔", "licked": "舔過",
  "sniff": "嗅", "sniffs": "嗅", "sneeze": "打噴嚏", "sneezes": "打噴嚏",
  "sneezing": "打噴嚏", "snore": "打鼾", "snores": "打鼾", "snoring": "打鼾",
  "yawn": "打呵欠", "stretch": "伸展", "stretches": "伸展",
  "blink": "眨眼", "blinks": "眨眼", "stare": "盯著看", "stared": "盯著看",
  "nod": "點頭", "nodded": "點頭過",
  "kneel": "跪", "kneels": "跪", "lean": "倚", "leans": "倚",
  "tap": "輕拍", "taps": "輕拍", "clap": "拍手", "claps": "拍手",
  "hit": "打", "hits": "打", "hold": "拿著", "kiss": "親吻",
  "wave": "揮手", "waved": "揮手過", "wand": "魔杖",
  "fell": "掉下", "falls": "掉落", "fall": "掉", "falling": "掉落中",
  "rise": "升起", "rises": "升起", "rose": "升起過", "rolled": "滾過", "rolls": "滾",
  "float": "漂浮", "floated": "漂浮過", "sail": "航行", "sailed": "航行過",
  "ride": "騎", "rode": "騎過", "rides": "騎",
  "dive": "潛", "dig": "挖", "digs": "挖", "dump": "倒",
  "plant": "種", "grow": "成長", "grew": "成長過", "grown": "長大",
  "burn": "燒", "burns": "燒", "burned": "燒過", "burning": "燃燒",
  "buried": "埋葬", "bury": "埋", "sink": "沉", "sinks": "沉",
  "sells": "賣", "sold": "賣過", "drips": "滴", "drip": "滴",
  "blow": "吹", "blows": "吹", "blew": "吹過",
  "shake": "搖", "shakes": "搖", "shaking": "顫抖", "shaky": "搖晃",
  "tremble": "顫抖", "lift": "舉", "boom": "轟",
  "thump": "重擊", "thumps": "重擊", "tick": "滴答", "ticks": "滴答",
  "wash": "洗", "washes": "洗",
  "fetch": "取", "fetched": "取過",
  "kept": "保留", "keep": "保持", "keeps": "保持", "keeping": "保持",
  "step": "步", "steps": "踏", "stepped": "踏過",
  "tied": "綁住", "tie": "綁", "knotted": "打結",
  "noted": "注意到", "noted": "注意",
  "ran": "跑過",
  "rang": "響過", "ring": "鈴",
  "called": "叫過", "calls": "叫", "call": "叫",
  "shaped": "形狀", "shape": "形狀",

  // misc nouns - story/food/object
  "story": "故事", "stories": "故事", "tale": "故事", "tales": "故事",
  "book": "書", "books": "書", "page": "頁", "word": "字", "words": "單字",
  "name": "名字", "names": "名字", "voice": "聲音", "sound": "聲音", "music": "音樂",
  "noise": "噪音", "silence": "寂靜", "tone": "語調", "sigh": "嘆息",
  "sighs": "嘆氣", "tear": "眼淚", "tears": "眼淚", "joke": "笑話", "jokes": "笑話",
  "promise": "承諾", "promises": "承諾", "secret": "秘密", "secrets": "秘密",
  "letter": "信", "letters": "信", "wish": "願望", "wishes": "願望",
  "idea": "想法", "ideas": "想法", "thing": "東西", "things": "東西",
  "item": "東西", "image": "影像", "size": "大小",
  "trip": "旅行", "race": "比賽", "game": "遊戲", "games": "遊戲",
  "match": "比賽", "prize": "獎品", "task": "任務", "job": "工作", "work": "工作",
  "works": "工作", "process": "過程", "way": "方式", "step": "步驟",
  "pace": "節奏", "purpose": "目的", "passion": "熱情",
  "luck": "運氣", "lucky": "幸運", "news": "消息", "problem": "問題",
  "answer": "答案", "question": "問題",
  "money": "錢", "gold": "金子", "stone": "石頭", "silver": "銀",
  "iron": "鐵", "glass": "玻璃", "paper": "紙", "ink": "墨水",
  "cloth": "布", "rope": "繩子", "ropes": "繩子", "yarn": "毛線",
  "rope": "繩子", "string": "線", "needle": "針", "key": "鑰匙", "keys": "鑰匙",
  "key": "鑰匙", "lock": "鎖", "locks": "鎖", "locked": "鎖住",
  "hat": "帽子", "hats": "帽子", "cap": "帽子", "boots": "靴子", "boot": "靴子",
  "coat": "外套", "robe": "長袍", "dress": "洋裝", "shirt": "襯衫", "shirts": "襯衫",
  "shoe": "鞋", "shoes": "鞋", "slippers": "拖鞋", "sandals": "涼鞋",
  "socks": "襪子", "sock": "襪子", "clogs": "木鞋", "uniform": "制服",
  "ring": "戒指", "rings": "戒指", "crown": "皇冠",
  "sword": "劍", "swords": "劍", "arrow": "箭", "stick": "棍子", "log": "原木",
  "logs": "原木", "broom": "掃帚", "torch": "火把", "lamp": "燈",
  "drum": "鼓", "bell": "鈴", "bells": "鈴", "flag": "旗子", "pole": "桿",
  "doll": "娃娃", "ball": "球", "toy": "玩具", "toys": "玩具",
  "boat": "船", "boats": "船", "cart": "車", "cab": "計程車",
  "phone": "電話", "alarm": "鬧鐘", "timer": "計時器",
  "map": "地圖", "mat": "墊子", "tile": "瓷磚", "spoon": "湯匙",
  "fence": "圍籬", "fences": "圍籬", "ladders": "梯子", "wheels": "輪子",
  "sign": "標誌", "shower": "淋浴", "drum": "鼓",

  // food
  "food": "食物", "meal": "餐", "meals": "餐",
  "breakfast": "早餐", "dinner": "晚餐", "lunch": "午餐", "feast": "盛宴",
  "rice": "米", "bread": "麵包", "soup": "湯", "salt": "鹽", "sugar": "糖",
  "cheese": "起司", "butter": "奶油", "meat": "肉", "beef": "牛肉",
  "sausage": "香腸", "fruit": "水果", "apple": "蘋果", "peach": "桃子",
  "plum": "李子", "tomato": "番茄", "honey": "蜂蜜", "carrot": "紅蘿蔔",
  "egg": "蛋", "eggs": "蛋", "noodles": "麵", "milk": "牛奶",
  "curry": "咖哩", "dumpling": "餃子", "dumplings": "餃子",
  "bone": "骨頭", "snack": "點心", "cake": "蛋糕",
  "jam": "果醬", "icing": "糖霜",

  // misc remaining
  "energy": "能量", "speed": "速度", "strength": "力量", "fight": "戰鬥",
  "pain": "痛", "anger": "憤怒", "joy": "喜悅", "grace": "優雅",
  "heart": "心", "wonder": "驚奇", "spell": "咒語", "spells": "咒語",
  "magic": "魔法", "trick": "把戲", "spark": "火花",
  "festival": "節慶", "war": "戰爭", "peace": "和平", "boredom": "無聊",
  "scarred": "有疤", "ruined": "毀壞",
  "thing": "東西", "process": "過程", "practice": "練習",
  "present": "禮物", "gift": "禮物",

  // adverbs / connectives often used
  "because": "因為", "if": "如果", "but": "但是", "though": "雖然",
  "while": "當", "until": "直到", "before": "之前", "after": "之後",
  "as": "當", "than": "比", "so": "所以", "however": "然而",
  "really": "真的", "truly": "真正", "actually": "其實", "almost": "幾乎",
  "even": "甚至", "just": "只是", "only": "只有", "instead": "反而",

  // additional A2 vocabulary from word-hints
  "afford": "負擔得起", "atone": "贖罪", "harm": "傷害",
  "agree": "同意", "agreed": "同意過", "argue": "爭吵", "argued": "爭吵過",
  "accept": "接受", "claim": "聲稱", "complain": "抱怨", "begged": "懇求過",
  "beg": "懇求", "begs": "懇求", "promise": "答應", "promised": "答應過",
  "ally": "盟友", "guard": "守衛", "owns": "擁有", "rents": "租",
  "expect": "期待", "behave": "表現", "boasts": "誇耀", "brags": "吹噓",
  "flatters": "奉承", "warn": "警告", "save": "拯救",
  "watch": "看守", "saved": "救過",
  "stack": "堆", "stock": "存貨", "stir": "攪", "skim": "撇開",
  "mount": "上", "moor": "停泊",
  "lend": "借", "borrowed": "借過", "lift": "舉",
  "purchase": "購買",
  "wove": "編織過",
  "rang": "響過",
  "calmly": "冷靜地", "softly": "輕輕地", "joyful": "喜悅",

  // additional one-offs from misses
  "hush": "噓", "halt": "停止", "hurry": "趕快",
  "moan": "呻吟", "snorts": "哼", "snort": "哼",
  "hum": "哼", "purr": "呼嚕",
  "frowns": "皺眉", "smug": "得意",
  "kindness": "善意",
  "respond": "回應",
  "carved": "雕刻過",
  "sample": "樣本", "packet": "小包", "pad": "墊子",
  "shaved": "刮過", "shaves": "刮鬍子",
  "ward": "病房",
  "umbrella": "雨傘", "porch": "門廊",
  "tour": "旅遊", "valley": "山谷",
  "lacy": "蕾絲的", "tipped": "傾斜", "tide": "潮汐",
  "thyme": "百里香", "jasmine": "茉莉",
  "jaw": "下顎", "jet": "噴射", "jog": "慢跑", "join": "加入",
  "moan": "呻吟", "moor": "停泊", "mount": "登山",
  "welcome": "歡迎", "welkin": "天空",
  "gentile": "外邦人", "genuine": "真實",
  "ideal": "理想", "image": "圖像",
  "peel": "剝皮", "pool": "水池",
  "removed": "移除", "rents": "出租",
  "scratches": "抓痕",
  "search": "搜尋", "searches": "搜尋",
  "sober": "嚴肅",
  "tone": "語氣", "tour": "旅行", "tumbles": "翻滾",
  "wand": "魔杖", "weak": "虛弱",
  "wickedly": "邪惡地",
  "loves": "愛", "loved": "愛過", "missed": "錯過", "moved": "搬家過",
  "needed": "需要過",
  "stayed": "留下",
  "wave": "揮手", "waved": "揮手過",
  "whispers": "低語",
  "thinks": "想", "thinking": "在想",
  "served": "服侍過", "serves": "服侍",
  "stretches": "伸展",
  "stretches": "伸展",
  "smile": "笑容", "smiles": "微笑",
  "smelling": "聞著", "smell": "聞",
  "feared": "害怕過", "feared": "害怕過",
  "called": "呼喚過",
  "took": "拿過",

  // final patch words (round 2)
  "straw": "稻草", "stray": "流浪的", "foreign": "外國的",
  "fun": "好玩", "curls": "捲曲", "kills": "殺", "corner": "角落",
  "aloud": "大聲", "sharp": "尖", "clean": "乾淨", "clear": "清楚",
  "cream": "奶油色", "gross": "噁心", "forth": "向前",
  "heat": "熱度", "roars": "吼", "naps": "打盹",
  "powerful": "強大", "steady": "穩定", "relaxed": "放鬆",
  "mate": "夥伴", "oils": "油", "hello": "嗨", "marry": "結婚",
  "western": "西方", "camp": "營地", "everything": "全部",
  "become": "變成", "blank": "空白", "brain": "腦袋",
  "caught": "抓到", "dear": "親愛的", "quite": "相當", "quit": "放棄",
  "bump": "撞", "pump": "幫浦", "added": "加了", "crowd": "人群",
  "steal": "偷", "broad": "寬", "dashes": "衝", "dares": "敢",
  "shall": "將", "meditate": "冥想", "medium": "中等",

  // name placeholders & proper names (keep literal)
  "{catname}": "{catName}", "{dogname}": "{dogName}",
  "mochi": "Mochi", "hana": "Hana", "hanako": "Hanako",
  "momoko": "Momoko", "momotaro": "桃太郎",
  "ye xian": "葉限", "yexian": "葉限",
  "chang'e": "嫦娥", "houyi": "后羿",
  "kipling": "Kipling", "cinderella": "Cinderella",
  "baba yaga": "Baba Yaga",
  "djinn": "Djinn", "camel": "駱駝",

  // misc additions from miss list
  "answer": "回答", "asks": "問", "answers": "回答",
  "arms": "手臂",
  "buy": "買", "buys": "買",
  "buys": "買",
  "cara": "親愛的",
  "cheers": "歡呼", "claps": "拍手", "frowns": "皺眉",
  "drops": "落下",
  "fights": "戰鬥", "feeds": "餵食",
  "lifts": "舉起", "licks": "舔",
  "lists": "列出", "lit": "點亮", "lifted": "舉起",
  "ride": "騎", "rises": "升起",
  "saw": "看見", "say": "說",
  "stand": "站", "stands": "站",
  "stops": "停", "stood": "站過",
  "stares": "盯", "stared": "盯著",
  "starts": "開始",
  "takes": "拿", "tell": "說", "tells": "告訴", "told": "告訴過",
  "turns": "轉", "turned": "轉",
  "tried": "試過", "trots": "小跑", "trot": "小跑",
  "wakes": "醒", "wants": "想要",
  "walks": "走", "watches": "看", "waves": "揮",
  "writes": "寫",
  "speaks": "說",
};

// Common phrase mappings (multi-word fixed expressions)
const PHRASES = {
  "good morning": "早安", "good night": "晚安", "good bye": "再見", "goodbye": "再見",
  "goodnight": "晚安", "good day": "日安", "good luck": "好運", "good news": "好消息",
  "bad news": "壞消息", "funny news": "好笑的消息", "old news": "舊消息",
  "right away": "馬上", "no right away": "不要馬上", "long ago": "很久以前",
  "of course": "當然", "no way": "不會吧", "no more": "不再", "no one": "沒人",
  "no use": "沒用", "no door": "沒門", "no fire": "沒火", "no food": "沒食物",
  "no friend": "沒朋友", "no story": "沒故事", "no man": "沒人", "no with anger": "生氣地說不",
  "yes sir": "是的先生", "all day": "整天", "all night": "整晚",
  "at home": "在家", "at school": "在學校", "at noon": "中午", "at night": "晚上",
  "at last": "終於", "at last she spoke": "她終於說話", "at the end": "在最後",
  "at the beginning": "一開始", "at midnight": "在午夜", "at dawn": "在黎明",
  "at sunrise": "日出時", "at sunset": "日落時", "at sundown": "日落時",
  "at her feet": "在她腳邊", "at the gate": "在門口",
  "at the lake": "在湖邊", "at the sea": "在海邊", "at the shoe": "在鞋邊",
  "at the sky": "在天空", "at the snow": "在雪地", "at the front door": "在前門",
  "at the empty pond": "在空池塘邊",
  "in front": "前面", "in love": "戀愛",
  "in silence": "在沉默中", "in spring": "在春天", "in summer": "在夏天",
  "in the boat": "在船上", "in the book": "在書裡", "in the corner": "在角落",
  "in the desert": "在沙漠", "in the forest": "在森林裡",
  "in the grass": "在草地", "in the jar": "在罐子裡", "in the kitchen": "在廚房",
  "in the nest": "在鳥巢", "in the pond": "在池塘", "in the pot": "在鍋裡",
  "in the river": "在河裡", "in the tree": "在樹上", "in the woods": "在森林",
  "in the yard": "在院子裡", "in a barn": "在穀倉裡", "in a boat": "在船上",
  "in a box": "在盒子裡", "in a cage": "在籠子裡", "in a cave": "在洞穴",
  "in a hole": "在洞裡", "in a hurry": "匆忙", "in a net": "在網中",
  "in a tree": "在樹上", "in a yard": "在院子裡", "in a wood": "在森林",
  "in a wide field": "在寬闊田野", "in a tall tree": "在高樹上",
  "in a small house": "在小屋裡", "in a deep well": "在深井裡",
  "in a deep cave": "在深洞", "in a small cave": "在小洞", "in a cold cave": "在冷洞",
  "in a tower": "在塔裡", "in a wooden box": "在木盒裡",
  "in a paper bag": "在紙袋裡", "in a soft cloth": "在軟布裡",
  "in a glass jar": "在玻璃罐", "in a dream": "在夢裡",
  "in a big city": "在大城市",
  "in her chair": "在她椅子上", "in her lap": "在她大腿上",
  "in her new chair": "在她的新椅子上", "in her old chair": "在她的舊椅子上",
  "in his ear": "在他耳邊", "in his hand": "在他手裡", "in his mouth": "在他嘴裡",
  "in his paw": "在他爪子裡", "in his tail": "在他尾巴上",
  "back home": "回家", "back to wall": "回到牆邊", "back in her bag": "回到她袋子裡",
  "back along the path": "沿著路回去",
  "across the city": "穿越城市", "across the desert": "穿越沙漠",
  "across the lake": "穿過湖", "across the sea": "穿越海洋", "across the sky": "穿越天空",
  "around": "周圍", "around the room": "繞著房間",
  "all at once": "一下子", "all the cities": "所有的城市", "all the deserts": "所有的沙漠",
  "all the seas": "所有的海", "all the stars": "所有的星星",
  "above me": "在我上方", "below me": "在我下方",
  "by the gate": "在門邊", "by the river": "河邊", "by the sea": "海邊",
  "by her chair": "在她椅子旁", "by a deep river": "在深河邊", "by a fire": "在火邊",
  "by fire": "用火", "by force": "用力", "by itself": "自己",
  "by luck": "靠運氣", "by waiting": "用等待", "by water": "用水",
  "to grandma's yard": "去奶奶的院子", "grandma's yard": "奶奶的院子",
  "to a shop": "去商店", "to a station": "去車站", "to a park": "去公園",
  "to a market": "去市場", "to a branch": "到樹枝", "to a cloud": "到雲端",
  "to a fence": "到圍籬", "to a nest": "到鳥巢",
  "to the city": "到城市", "to the forest": "到森林", "to the hills": "到山丘",
  "to the market": "到市場", "to the park": "去公園", "to the path": "去小路",
  "to the pond": "去池塘", "to the pot": "到鍋裡", "to the queen": "到女王那",
  "to the river": "到河邊", "to the sea": "到海邊", "to the woods": "到森林",
  "to throw away": "丟掉", "to trot": "小跑步",
  "near a lake": "湖邊", "near the gate": "門邊", "next door": "隔壁",
  "next month": "下個月", "next week": "下週", "next year": "明年",
  "next to": "在旁邊",
  "on a hill": "在山丘上", "on a wall": "在牆上", "on the bed": "在床上",
  "on the book": "在書上", "on the door": "在門上", "on the floor": "在地板",
  "on the grass": "在草地", "on the ground": "在地上", "on the road": "在路上",
  "on the roof": "在屋頂", "on the table": "在桌上", "on the wall": "在牆上",
  "on a high branch": "在高樹枝", "on a low rock": "在低石頭上",
  "on a sunny rock": "在曬太陽的石頭上",
  "on his back": "在他背上", "on his nose": "在他鼻子上", "on my head": "在我頭上",
  "on the cold day": "在冷天裡", "on the cold floor": "在冷地板",
  "on the cold stones": "在冷石頭上", "on the dry leaves": "在乾葉子上",
  "on the first night": "在第一晚", "on the soft grass": "在軟草地",
  "on the third morning": "在第三天早上", "on the seventh week": "在第七週",
  "on the warm rice": "在溫熱的米上",
  "out and cold": "在外又冷", "out of town": "出城",
  "outdoors": "戶外", "outside the door": "門外",
  "over his back": "蓋在他背上", "over his foot": "蓋在他腳上",
  "over his nose": "蓋在他鼻子上", "over his tail": "蓋在他尾巴上",
  "side to side": "左右", "step by step": "一步一步",
  "round and round": "繞圈圈",
  "up at her": "看向她", "up a hill": "上山", "up the river": "上游",
  "down a road": "沿著路", "down at ground": "看著地面",
  "under the bed": "床下", "under the chair": "椅子下",
  "under the moon": "月光下", "under the table": "桌子下", "under the tree": "樹下",
  "under a shady bush": "在陰涼灌木下",
  "with a cloth": "用一塊布", "with a kiss": "用一個吻",
  "with a loud bang": "砰一聲", "with a smile": "帶著微笑",
  "with a stick": "用一根棍子", "with anger": "生氣地", "with angry eyes": "用生氣的眼神",
  "with both hands": "用兩手", "with claps": "拍著手",
  "with empty eyes": "空洞的眼神", "with empty hands": "兩手空空",
  "with fast feet": "用快腳步", "with great care": "非常小心",
  "with loud song": "大聲唱歌", "with money": "有錢", "with my eyes closed": "閉著眼睛",
  "with one eye open": "睜一隻眼", "with one foot": "用一隻腳",
  "with proud eyes": "驕傲的眼神", "with quiet care": "輕輕地照顧",
  "with shouts": "大聲喊", "with silence": "沉默地", "with sleep": "睡著",
  "with sleepy eyes": "睡眼惺忪", "with songs": "用歌聲", "with strict rules": "嚴格規定",
  "with surprise": "驚訝地", "without making a sound": "沒發出聲音",
  "after dinner": "晚餐後",
  "very angry": "很生氣", "very brave": "很勇敢", "very bright": "很亮",
  "very cold": "很冷", "very fast": "很快", "very full": "很飽",
  "very hot": "很熱", "very hungry": "很餓", "very kindly": "很親切",
  "very lazy": "很懶", "very light": "很輕", "very long ago": "很久很久以前",
  "very loud": "很大聲", "very proud": "很驕傲", "very quiet": "很安靜",
  "very sad": "很傷心", "very sleepy": "很想睡", "very softly": "很輕地",
  "very still": "很靜止", "very surprised": "很驚訝", "very sweet": "很甜",
  "very tall": "很高", "very wet": "很濕",
  "fell asleep": "睡著了", "fell down": "跌倒",
  "go home": "回家", "go to sleep": "去睡覺", "go to school": "去上學",
  "go to her": "去找她", "go far away": "走遠", "go to the island": "去島上",
  "go back home": "回家", "go even when you are scared": "害怕也要走",
  "going to sleep": "去睡覺",
  "look up": "向上看", "looked up": "抬頭", "looking for food": "找食物",
  "ran away": "逃走", "ran out": "用完", "ran fast": "跑得快",
  "ran very fast": "跑得很快", "ran faster": "跑更快", "ran without looking": "沒看就跑",
  "ran home alone": "獨自跑回家",
  "runs away": "跑開", "runs away fast": "快速逃走", "runs for a bit": "跑了一下",
  "runs home": "跑回家", "runs outside": "跑到外面", "runs to the river": "跑到河邊",
  "stand still": "站著不動", "stand up": "起立", "stand stiff": "僵硬站著",
  "stand and eat": "站著吃", "stand or sit": "站或坐", "stands taller": "站得更高",
  "stands up": "站起來",
  "sit down": "坐下", "sit and eat": "坐下吃", "sit tight": "坐穩",
  "sits down": "坐下", "sits and opens a book": "坐下打開書",
  "lie down": "躺下", "lay down": "躺下",
  "step back": "退一步", "stop walking": "停下腳步",
  "wait for help": "等待救援", "walks away": "走開",
  "wakes up": "醒來", "stays quiet": "保持安靜",
  "keep going": "繼續前進", "keep going steadily": "穩穩往前走",
  "keep going to the end": "一直走到底",
  "stay at home": "待在家", "stay cold": "保持冷", "stay outside": "待在外面",
  "stay out": "待在外", "stayed alone": "獨自留下", "stayed home": "留在家",
  "feed it": "餵牠", "feed the cat now": "現在餵貓", "feeds the cat": "餵貓",
  "feeds it to the dog": "餵狗", "feed her warm food": "餵她熱食",

  // single-word fallback already in DICT — these are common phrase forms
  "give up": "放棄", "build a house": "蓋房子", "build a big tower": "蓋大塔",
  "built a house": "蓋了房子", "builds a big tower": "蓋大塔",
  "clean the yard": "打掃院子", "climb up": "爬上去", "climb the wall": "爬牆",
  "close to grandma": "靠近奶奶", "cook the meat": "煮肉",
  "cooks dinner": "煮晚餐", "cooks it for dinner": "煮來當晚餐",
  "covered his face": "蓋住他的臉", "covers the chair": "蓋住椅子",
  "cried softly": "輕聲哭", "cries": "哭",
  "did not stop": "沒有停",
  "dig the ground": "挖土", "digs a hole": "挖洞",
  "do not stay home": "不要留在家", "do not eat sand": "不要吃沙",
  "do not be lazy": "不要懶惰", "do not sleep late": "不要晚睡",
  "do work or leave": "做事或走人",
  "drinks": "喝", "drops": "掉",
  "eat grass": "吃草", "eat more sausage": "吃更多香腸",
  "eats a bone": "啃骨頭",
  "fights the lion": "對抗獅子", "find a friend": "找朋友",
  "find a king to save you": "找國王救你", "find the cat owner": "找貓主人",
  "find food": "找食物", "five times": "五次", "ten times": "十次",
  "ten weeks": "十週",
  "fly to the roof": "飛上屋頂", "fly by fly": "一隻蒼蠅接一隻",
  "for one minute": "一分鐘",
  "from a desert": "從沙漠", "from anger": "因生氣", "from cold": "因為冷",
  "from crying": "因為哭", "from joy": "因為開心",
  "from running": "因為跑步", "from singing": "因為唱歌", "from sleep": "從睡夢中",
  "from the kitchen": "從廚房", "from the rain": "從雨中", "from the sea": "從海",
  "fresh grass": "新鮮的草", "fresh rice": "新鮮的飯",
  "got lost": "迷路", "grew big": "長大",
  "have nothing else": "沒別的", "he has nothing else to do": "他沒別的事做",
  "he has nowhere else": "他無處可去",
  "kept all the food": "把所有食物留著", "kept walking": "繼續走",
  "led the way": "帶路", "leans": "倚靠",
  "left her there": "把她留在那", "lifts the book": "舉起書",
  "lifts the net": "拉起網",
  "long ropes": "長繩子",
  "made gold": "造出金子",
  "make food": "做食物", "make by hand": "用手做",
  "make friends with bugs": "和蟲做朋友",
  "many years": "很多年",
  "married her": "娶了她", "married someone new": "娶別人",
  "missed them": "想念他們",
  "moved away": "搬走",
  "more afraid": "更害怕", "more afraid now": "更怕了", "more angry": "更生氣",
  "more cold": "更冷", "more dark": "更暗", "more empty": "更空",
  "more grass": "更多草", "more sad": "更傷心", "more scared": "更害怕",

  // generic story answers
  "i don't know": "我不知道", "i don't know.": "我不知道",
  "yes, i will": "好，我會", "no, i won't": "不，我不要",
  "yes, very loud": "對，很大聲", "yes very loudly": "對，很大聲",
  "no she did not": "她沒有", "yes she did": "她有", "no, she did not": "不，她沒有",
  "yes, she did": "對，她有", "yes, he did": "對，他有", "no, he did not": "不，他沒有",
  "yes, they did": "對，他們有", "no, they did not": "不，他們沒有",
  "yes, right away": "對，馬上", "no, never": "不，從來沒有", "no, never again": "不再",
  "yes, at last": "終於", "yes, very loudly": "對，很大聲",
  "yes, a lot": "對，很多", "only a little": "只有一點",
  "no, she stayed silent": "沒，她保持沉默",
  "no, she was sleeping": "沒，她在睡覺",
  "no, she went on": "沒，她繼續說",
  "no, he ran away": "不，他逃走了",
  "no, he was always this": "不，他本來就是這樣",
  "no, her cat did": "不，是她的貓",
  "no, he does not": "不，他不會",
  "no, he hides instead": "不，他躲起來",
  "no, he keeps walking": "不，他繼續走",
  "no, it was magic": "不，是魔法",
  "yes, he changed color": "對，他變了顏色",
  "yes, he worked hard": "對，他很努力",
  "yes, she ran home": "對，她跑回家",
  "yes, she was mean": "對，她很壞",
  "yes, they are crows": "對，是烏鴉",
  "yes, they are ducks": "對，是鴨子",
  "yes, they are pigeons": "對，是鴿子",
  "yes after a quiet moment": "靜了一下後說好",
  "yes she was scared": "對她很害怕",
  "yes, he shouts loud": "對，他大聲喊",
  "yes, he taps hare": "對，他輕拍兔子",

  // closure
  "the end": "結束",
};

// Phrase entries: lowercase keys
for (const k of Object.keys(PHRASES)) {
  PHRASES[k.toLowerCase()] = PHRASES[k];
}

// ============================================================
// translate(en) — main translator
// ============================================================
function lookupWord(w) {
  const lo = w.toLowerCase();
  if (DICT[lo]) return DICT[lo];
  if (HINTS[lo]) return HINTS[lo];
  // handle common inflections
  if (lo.endsWith('s') && DICT[lo.slice(0,-1)]) return DICT[lo.slice(0,-1)];
  if (lo.endsWith('s') && HINTS[lo.slice(0,-1)]) return HINTS[lo.slice(0,-1)];
  if (lo.endsWith('ed') && DICT[lo.slice(0,-2)]) return DICT[lo.slice(0,-2)] + '過';
  if (lo.endsWith('ed') && HINTS[lo.slice(0,-2)]) return HINTS[lo.slice(0,-2)] + '過';
  if (lo.endsWith('ing') && DICT[lo.slice(0,-3)]) return DICT[lo.slice(0,-3)] + '中';
  if (lo.endsWith('ing') && HINTS[lo.slice(0,-3)]) return HINTS[lo.slice(0,-3)] + '中';
  if (lo.endsWith('ly') && DICT[lo.slice(0,-2)]) return DICT[lo.slice(0,-2)] + '地';
  if (lo.endsWith('ly') && HINTS[lo.slice(0,-2)]) return HINTS[lo.slice(0,-2)] + '地';
  if (lo.endsWith('er') && DICT[lo.slice(0,-2)]) return '更' + DICT[lo.slice(0,-2)];
  if (lo.endsWith('er') && HINTS[lo.slice(0,-2)]) return '更' + HINTS[lo.slice(0,-2)];
  if (lo.endsWith("'s") && DICT[lo.slice(0,-2)]) return DICT[lo.slice(0,-2)] + '的';
  if (lo.endsWith("'s") && HINTS[lo.slice(0,-2)]) return HINTS[lo.slice(0,-2)] + '的';
  return null;
}

function translate(en) {
  if (!en) return en;
  const orig = en;
  const trimmed = en.trim();

  // Preserve placeholders {catName} / {dogName}
  const placeholderMap = {};
  let working = trimmed;
  working = working.replace(/\{catName\}/g, '〈〈CAT〉〉').replace(/\{dogName\}/g, '〈〈DOG〉〉');

  const lo = working.toLowerCase();

  // Direct phrase hit
  if (PHRASES[lo]) {
    return PHRASES[lo].replace(/〈〈CAT〉〉/g, '{catName}').replace(/〈〈DOG〉〉/g, '{dogName}');
  }

  // Just a placeholder
  if (working === '〈〈CAT〉〉') return '{catName}';
  if (working === '〈〈DOG〉〉') return '{dogName}';

  // Single-word lookup
  if (!/\s/.test(working)) {
    const w = lookupWord(working);
    if (w) return w.replace(/〈〈CAT〉〉/g, '{catName}').replace(/〈〈DOG〉〉/g, '{dogName}');
  }

  // Fall back to overrides (manual phrases) — see OVERRIDES below
  if (OVERRIDES[lo]) {
    return OVERRIDES[lo].replace(/〈〈CAT〉〉/g, '{catName}').replace(/〈〈DOG〉〉/g, '{dogName}');
  }

  // Compositional fallback — word-by-word concatenation with light cleanup
  const tokens = working.split(/\s+/);
  const out = [];
  for (const tok of tokens) {
    if (tok === '〈〈CAT〉〉') { out.push('{catName}'); continue; }
    if (tok === '〈〈DOG〉〉') { out.push('{dogName}'); continue; }
    const cleaned = tok.replace(/[.,!?;:'"]/g, '');
    const t = lookupWord(cleaned) || cleaned;
    out.push(t);
  }
  return out.join('');
}

export { translate, DICT, PHRASES, lookupWord };
